global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # For services running on host machine
  - job_name: "mlflow-model"
    static_configs:
      - targets: ["host.docker.internal:5000"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "ml-custom-metrics"
    static_configs:
      - targets: ["host.docker.internal:8000"]
    metrics_path: /metrics
    scrape_interval: 10s

  # For containerized services
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s